### PR TITLE
bug: cannot fetch mint transactions

### LINKED ISSUE #1199: Cannot fetch Mint transactions through Provider
In `fuels-core/src/types/wrappers/transaction_response.rs` 

```
 let transaction = match client_response.transaction {
            Transaction::Script(tx) => TransactionType::Script(ScriptTransaction::from(tx)),
            Transaction::Create(tx) => TransactionType::Create(CreateTransaction::from(tx)),
            Transaction::Mint(_) => unimplemented!(),
        };
```

`unimplemented!()` will cause the entire function to panic, `None` should be returned instead.

### PR DESCRIPTION
**Pull request by segfault-magnet**
closes #1199 

Mint transactions can now be fetched through the `Provider`. Implemented what made sense for `Mint`, left the rest as `unimplemented!`. Without some hefty redesign don't see what other option is there but to violate the LSP (L for Liskov).

Decided to wrap `Mint`, so that users may extract the id, outputs, etc, without having to know about the various traits from fuel.

### Checklist
- [x] I have linked to any relevant issues.
- [ ] I have updated the documentation.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary labels.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

File: packages/fuels-core/src/types/wrappers/transaction.rs [hunk 1]
```diff
@@ -136,10 +182,15 @@ impl From<TransactionType> for FuelTransaction {
         match value {
             TransactionType::Script(tx) => tx.into(),
             TransactionType::Create(tx) => tx.into(),
+            TransactionType::Mint(tx) => tx.into(),
         }
     }
 }
 
+fn unsupported_mint_operation(operation: &str) -> ! {
+    unimplemented!("Calling `{operation}` on Mint transactions is unsupported!");
```
Comment (Voxelot) [inline packages/fuels-core/src/types/wrappers/transaction.rs:191]: Maybe it'd be better to just return an error instead of panicking? Imo we shouldn't have any public apis exposed to users that allow them to cause a panic.

**Review by MujkicA — COMMENTED** [review]
Does `Mint` have to implement `Transaction`? We use the trait as a common interface for `Create` and `Script` when submitting them to the provider and AFAIK submitting `Mint` currently makes no sense.
IMO it's better to not implement `Transaction` here since it will also guard against passing the tx where it doesn't belong.

On the other hand a transaction that is not `Transaction` could be confusing. Maybe renaming the trait to something like `SubmittableTransaction` would make sense.

**Comment by Voxelot** [comment]
In the VM we use a trait called `ExecutableTransaction` so that it only accepts create or script txs

**Comment by segfault-magnet** [comment]
> Does `Mint` have to implement `Transaction`? We use the trait as a common interface for `Create` and `Script` when submitting them to the provider and AFAIK submitting `Mint` currently makes no sense.

If you take a closer look you'll notice that Mint doesn't implement `Transaction`. Rather it is the `TransactionType` enum that implements it. Its `Transaction` implementation just delegates to the underlying transaction. But how do you delegate the methods that only make sense for `Create` of `Script` to the `Mint` transaction? This is the breaking of the LSP I mentioned above.

You also cannot implement something like `ExecutableTransaction` since you'll have the same problem -- what to do with the `Mint` variant? 

The only solution is not to implement anything for this enum and have it just be a bare enum, used so that we can return `Transactions` requested by the user via the `get_transactions` endpoint of the `Provider`.

I don't see the methods of `Transaction` being used with a `TransactionType` -- I think the goal was to circumvent the issues of the trait not being object safe by using an enum and just delegating to the variants. This, as mentioned above, falls apart with the introduction of `Mint`. 

I suggest we remove the `Transaction` impl from the `TransactionType` and have users match, extract the underlying transaction and then call whatever they like on it.

@MujkicA @Voxelot

File: packages/fuels-core/src/types/wrappers/transaction.rs (hunk 1 above)
Comment (segfault-magnet) [reply packages/fuels-core/src/types/wrappers/transaction.rs:191]: I started a discussion about not implementing this trait at all. If that for some reason isn't accepted, I'll change the trait so that methods that would have passed normally on a Script or Create will fail in the case of a Mint transaction.

**Review by digorithm — APPROVED** [review]

**Review by hal3e — DISMISSED** [review]
LGTM!

**Review by Br1ght0ne — APPROVED** [review]

**Review by Salka1988 — APPROVED** [review]

**Review by digorithm — APPROVED** [review]
