### PR TITLE
fix: remove spam from `fuel-core` when running tests

### LINKED ISSUE #495: test: remove the spam from `fuel-core` when testing without `fuel-core-lib` feature
* The fix in #479 does not work if `fuel-core-lib` feature is not enabled (which makes sense!)

### PR DESCRIPTION
**Pull request by iqdecay**
* This PR closes #495 by adding the `silent` option for running a Fuel node, which is enabled by default.

### CODE REVIEW

**Review by digorithm — APPROVED** [review]

File: packages/fuels-test-helpers/src/node.rs [hunk 1]
```diff
@@ -264,10 +265,15 @@ pub async fn new_fuel_node(
             args.push("--manual_blocks_enabled");
         }
 
-        let mut running_node = Command::new("fuel-core").args(args)
+        let mut command = Command::new("fuel-core");
+        if silent {
+            command
+                .stdin(Stdio::null())
```
Comment (segfault-magnet) [inline packages/fuels-test-helpers/src/node.rs:271]: Stdin should always be closed since we're not aiming to have an interactive experience with the spawned fuel-core process.

File: packages/fuels-test-helpers/src/node.rs [hunk 2]
```diff
@@ -264,10 +265,15 @@ pub async fn new_fuel_node(
...
+                .stdout(Stdio::null())
+                .stderr(Stdio::null());
+        }
+        let mut running_node =command.args(args)
```
Comment (segfault-magnet) [inline packages/fuels-test-helpers/src/node.rs:275]: It might be github, but this ws is weird

File: packages/fuels-test-helpers/src/node.rs (hunk 1 above)
Comment (digorithm) [reply packages/fuels-test-helpers/src/node.rs:271]: ^ Good point!

**Review by Salka1988 — APPROVED** [review]

**Review by segfault-magnet — APPROVED** [review]
