### PR TITLE
bug!: updating consensus parameters

### LINKED ISSUE #1561: Check for updates to cached ConsensusParameters
`Provider` caches ConsensusParameters without checking for updates. This can cause issues for long running services when the parameters change, e.g. the gas factor increases.

### PR DESCRIPTION
**Pull request by segfault-magnet**
- Closes #1561 
# Release notes

In this release, we:

- Made the `ConsensusParameters` cache expire-able in `Provider`

# Summary

The `Provider` now evicts the cached `ConsensusParameters` after the preconfigured TTL (defaulted to 60s).

You can change the TTL by doing:
```rust
    provider.set_cache_ttl(TtlConfig {
        consensus_parameters: Duration::from_secs(5),
    });
```

If you want to clear the cache immediately you can do so by:
```rust
    provider.clear_cache().await;
```

# Breaking Changes

The `consensus_parameters` method in `Provider` is now `async` and fallable:
```rust
    pub async fn consensus_parameters(&self) -> Result<ConsensusParameters>
```

The following methods have been removed:
- `base_asset_id` -- now acquired by `provider.consensus_parameters().await?.base_asset_id()`
- `chain_id` -- now acquired by `provider.consensus_parameters().await?.chain_id()`

# Checklist

- [x] All **changes** are **covered** by **tests** (or not applicable)
- [x] All **changes** are **documented** (or not applicable)
- [x] I **reviewed** the **entire PR** myself (preferably, on GH UI)
- [x] I **described** all **Breaking Changes** (or there's none)

### CODE REVIEW

File: packages/fuels-accounts/src/provider.rs [hunk 1]
```diff
@@ -166,12 +178,18 @@ impl Provider {
         tx: T,
     ) -> Result<TxStatus> {
         #[cfg(feature = "coin-cache")]
-        self.check_inputs_already_in_cache(&tx.used_coins(self.base_asset_id()))
+        let base_asset_id = {
+            let consensus_parameters = self.consensus_parameters().await?;
+            *consensus_parameters.base_asset_id()
+        };
```
Comment (hal3e) [inline packages/fuels-accounts/src/provider.rs:184]:
```suggestion
        let base_asset_id = *self.consensus_parameters().await?.base_asset_id();
```

File: packages/fuels-accounts/src/provider/cache.rs [hunk 2]
```diff
@@ -0,0 +1,277 @@
...
+        &mut self.client
+    }
+}
+
+impl<Client, Clk> CachedClient<Client, Clk>
+where
+    Client: CacheableRpcs,
+{
+    pub async fn clear(&self) {
+        let _ = self.cached_consensus_params.write().await.take();
```
Comment (hal3e) [inline packages/fuels-accounts/src/provider/cache.rs:88]:
```suggestion
        *self.cached_consensus_params.write().await = None;
```

File: packages/fuels-accounts/src/provider.rs [hunk 3]
```diff
@@ -814,17 +872,17 @@ impl DryRunner for Provider {
...
         _latest_chain_executor_version: Option<u32>,
     ) -> Result<Option<FuelTransaction>> {
         // We always delegate the estimation to the client because estimating locally is no longer
         // possible due to the need of blob storage
-        Ok(Some(self.client.estimate_predicates(tx).await?))
+        Ok(Some(self.uncached_client().estimate_predicates(tx).await?))
+    }
+
+    async fn consensus_parameters(&self) -> Result<ConsensusParameters> {
+        Provider::consensus_parameters(self).await
```
Comment (hal3e) [inline packages/fuels-accounts/src/provider.rs:886]:
```suggestion
        self.consensus_parameters().await
```

**Review by hal3e — APPROVED** [review]
LGTM

**Review by Salka1988 — APPROVED** [review]

**Review by MujkicA — APPROVED** [review]

File: packages/fuels-accounts/src/provider.rs (hunk 1 above)
Comment (segfault-magnet) [reply packages/fuels-accounts/src/provider.rs:184]: Ty. Gonna do these in a separate PR just so I  don't loose the precious approves.

File: packages/fuels-accounts/src/provider/cache.rs (hunk 2 above)
Comment (segfault-magnet) [reply packages/fuels-accounts/src/provider/cache.rs:88]: [Same](https://github.com/FuelLabs/fuels-rs/pull/1569#discussion_r1909149078)
