### PR TITLE
fix: prevent overflow while decoding param types

### LINKED ISSUE #1215: bug: `decode_multiple` can overflow
During a fuzzing campaign, it turned out that this test panics with an `attempt to add with overflow`:
```rust
        let param_types = vec![ParamType::Enum {
            variants: EnumVariants::new(vec![ParamType::Struct {
                fields: vec![
                    ParamType::StringArray(12514849900987264429),
                    ParamType::StringArray(7017071859781709229),
                ],
                generics: vec![],
            }])
            .unwrap(),
            generics: vec![],
        }];
        let bytes = vec![];
        let a = ABIDecoder::default().decode_multiple(&param_types, &bytes);
```

at the `decode_multiple` step.
We should probably enforce some upper limit on the length of `StringArray` and `Array`.

### PR DESCRIPTION
**Pull request by iqdecay**
Closes #1215 by fixing the way encoding size is computed

### CODE REVIEW

**Review by Br1ght0ne — APPROVED** [review]
LGTM!

File: packages/fuels-core/src/types/param_types.rs [hunk 1]
```diff
@@ -164,36 +159,68 @@ impl ParamType {
...
+            }
             _ => None,
-        }
+        };
+        Ok(heap_bytes_size)
     }
 
     /// Calculates the number of bytes the VM expects this parameter to be encoded in.
-    pub fn compute_encoding_in_bytes(&self) -> Option<usize> {
+    pub fn compute_encoding_in_bytes(&self) -> Result<usize> {
```
Comment (MujkicA) [inline packages/fuels-core/src/types/param_types.rs:181]: Maybe we can make this and the test a bit cleaner by adding a closure:

```rust
let overflow_error = || {
            error!(
                InvalidType,
                "Reached overflow while computing encoding size for {:?}",
                self
            )
        };
```

Then used it like this:

```rust
ParamType::Array(param, count) => param
                .compute_encoding_in_bytes()?
                .checked_mul(*count)
                .ok_or_else(overflow_error),
```

If the `Debug` representation contains more info than needed we can go for `Display`. Maybe the `Display` implementation will also be useful in other places where we return `InvalidType`.

**Review by digorithm — COMMENTED** [review]
Great job finding this issue and fixing it. LGTM, but I agree with @MujkicA's suggestions; it'll make a lot nicer to the eyes.

**Review by Br1ght0ne — APPROVED** [review]

**Review by digorithm — APPROVED** [review]

**Review by MujkicA — APPROVED** [review]

**Review by Salka1988 — APPROVED** [review]
