### PR TITLE
fix: support the new Sway array type format

### LINKED ISSUE #111: Fix support for arrays
The SDK had support for static non-string arrays when the format was `T[n]` as specified here https://github.com/FuelLabs/fuel-specs/blob/master/specs/protocol/abi.md#array

But now arrays in Sway are defined as `[T; size]` for type `T` and the generated ABI looks like `"type":"[T; size]"`. 

This broke the array support in the SDK and we should fix it by changing the parsing from `T[n]` to `[T; size]`. 

- [x] Change ABI parsing from `T[n]` to `[T; size]`;
- [x] Update all tests in harness to include the right json ABI;
- [x] Update the `fuel-specs`'s ABI section.

### PR DESCRIPTION
**Pull request by vnepveu**
This PR closes #111 by fixing the ABI parsing of the array type from `T[n]` to `[T; n]`.
It also refactors the parsing of `str[n]` parameters and implements tests for both parsing.

### CODE REVIEW

File: fuels-core/src/json_abi.rs [hunk 1]
```diff
@@ -516,41 +516,52 @@ pub fn parse_param(param: &Property) -> Result<ParamType, Error> {
...
+    let split: Vec<&str> = param.type_field.split("; ").collect();
+    if split.len() != 2 {
+        return Err(Error::InvalidType(format!(
+            "Expected parameter type `[T; n]`, found `{}`",
+            param.type_field
+        )));
     }
+    let (type_field, size) = (split[0], split[1]);
+    let type_field = type_field[1..].to_string();
+    let param_type = ParamType::from_str(&type_field).unwrap();
```
Comment (digorithm) [inline fuels-core/src/json_abi.rs:560]: We should avoid using `unwrap()` when it's possible / not too hard to avoid it. In this case here, it's not too hard to change `unwrap()` to `?` to better handle the error and avoid panicking. The error from parsing a bad `type_field` would be very cryptic to the end-user that could've misspelled the type in the JSON ABI.

File: fuels-core/src/json_abi.rs [hunk 2]
```diff
@@ -516,41 +516,52 @@ pub fn parse_param(param: &Property) -> Result<ParamType, Error> {
...
+
+    // Grab size the `n` in "[T; n]"
+    let size: usize = size[..size.len() - 1].parse().unwrap();
```
Comment (digorithm) [inline fuels-core/src/json_abi.rs:563]: Same comment here about `unwrap()`.

**Review by digorithm — CHANGES_REQUESTED** [review]
Looking great, good work on this. Just left some comments on better error handling.

File: fuels-core/src/json_abi.rs (hunk 1 above)
Comment (vnepveu) [reply fuels-core/src/json_abi.rs:560]: I'm still not used to this you're absolutely right

**Review by digorithm — APPROVED** [review]
